trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    echo "##vso[task.setvariable variable=FLUTTER_HOME]$(pwd)/flutter"
    echo "##vso[task.prependpath]$(pwd)/flutter/bin"
    flutter doctor
  displayName: 'Install Flutter'

- script: flutter pub get
  displayName: 'Install dependencies'

- script: flutter analyze
  displayName: 'Static Code Analysis'

- script: flutter test
  displayName: 'Run Unit Tests'

- script: flutter build apk --release
  displayName: 'Build APK'

- task: CopyFiles@2
  inputs:
    contents: 'build/app/outputs/flutter-apk/app-release.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy APK to Artifact Staging'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'apk'
  displayName: 'Publish APK Artifact'

- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    ./trivy fs --scanners vuln $(Build.SourcesDirectory)
  displayName: 'Run Trivy Vulnerability Scan'