trigger:
  - main

pool:
  name: 'Default'  # Usa el nombre del pool que configuraste

steps:
- script: |
    set FLUTTER_HOME=C:\flutter
    set PATH=%FLUTTER_HOME%\bin;%PATH%
    flutter doctor
  displayName: 'Set up Flutter'

- script: flutter pub get
  displayName: 'Install dependencies'

- script: flutter build apk --release
  displayName: 'Build APK'

- script: mkdir build\apkfile && move build\app\outputs\flutter-apk\app-release.apk build\apkfile\funesami.apk
  displayName: 'Move and Rename APK'

- script: dir build\apkfile
  displayName: 'List APK Directory'

- task: CopyFiles@2
  inputs:
    contents: 'build/apkfile/funesami.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy APK to Artifact Staging'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'apk'
  displayName: 'Publish APK Artifact'