trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Usar Python'

  - script: |
      sudo apt-get update -y
      sudo apt-get install -y curl unzip xz-utils zip libglu1-mesa
    displayName: 'Instalar dependencias necesarias'

  - script: |
      git clone https://github.com/flutter/flutter.git --depth 1 -b stable
      echo "##vso[task.setvariable variable=PATH]$PATH:$(pwd)/flutter/bin"
    displayName: 'Instalar Flutter'

  - script: |
      flutter --version
      flutter pub get
    displayName: 'Configurar Flutter'

  - script: |
      flutter build apk --release
    displayName: 'Construir APK'

  - script: |
      git config --global user.email "tu-email@example.com"
      git config --global user.name "tu-nombre"
      git checkout main
      mv build/app/outputs/flutter-apk/app-release.apk app-release.apk
      git add app-release.apk
      git commit -m "Agregar APK generado automáticamente"
      git push origin main
    displayName: 'Subir APK al repositorio'
