
name: Generar APK para Producción
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_apk_production:
    name: Generar y Subir APK a producción
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configurar usuario de GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          
      - name: Limpiar el proyecto Flutter (flutter clean)
        run: flutter clean
        
      - name: Instalar dependencias de Flutter
        run: flutter pub get
        
      - name: Crear CustomCard.dart en la ubicación correcta
        run: |
          mkdir -p lib/auth/presentation/Widgets
          cat > lib/auth/presentation/Widgets/CustomCard.dart << 'EOF'
          import 'package:flutter/material.dart';
          
          class CustomCard extends StatelessWidget {
            final Widget child;
            
            const CustomCard({Key? key, required this.child}) : super(key: key);
            
            @override
            Widget build(BuildContext context) {
              return Card(child: child);
            }
          }
          EOF
          
      - name: Generar APK en modo release
        run: flutter build apk --release
        
      - name: Mover y Commitear APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk app-release.apk
          git add app-release.apk
          git commit -m "Generado APK de producción"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
          
      - name: Subir APK como artefacto en GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: APK de Producción
          path: app-release.apk
